channels:
- conda-forge
dependencies:
- python=3.12.9
- pip<=24.3.1
- pip:
  - mlflow==3.8.1
  - cloudpickle==3.1.2
  - numpy==2.1.3
  - pandas==2.3.1
  - psutil==7.0.0
  - pyarrow==22.0.0
  - scikit-learn==1.7.1
  - scipy==1.16.1
name: mlflow-env
